name: obizplan
description: Functional MVP for HPP app
publish_to: "none"
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  url_launcher: ^6.2.5
  screenshot: ^3.0.0
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  go_router: ^14.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
